### ISSUE TITLE
instance system.adapter.zigbee2mqtt.0 terminated with code 1 (JS_CONTROLLER_STOPPED)

### ISSUE THREAD

**Issue by the-duke** [arteck/ioBroker.zigbee2mqtt#137]
### What happened?

Hallo ich freue mich über dieses schöne io-broker Adapter Projekt und wollte es ausprobieren.
Dabei startet die Adapter instanz immer wieder neu und verbindet sich nicht.
Es schein laut der Logs an einer npm Dependency des Adapters zu liegen, die einen Syntaxfehler enthält..?

### What did you expect to happen?

Das sich der Adapter mit meinem zibee2mqtt verbindet 

### How to reproduce it (minimal and precise)

Mein Setup ist folgendes:
- Iobroker läuft in einem Docker Container auf einem Synology NAS
- Mosquitto läuft in einem eigenen Container auf dem Synology Nas
-  zigbee2mqtt läuft auf einem Rasberry PI3 und ist laut FAQ konfiguriert (ip 192.168.1.4) und verbindet sich mit dem Mosquitto auf den NAS

-  die ioBroker.zigbee2mqtt Adaper-Instanz ist für die Verbindung via websocket zu RPI configuriert (192.168.1.4:8080)

### Adapter version

2.7.3

### Log

Restart adapter system.adapter.zigbee2mqtt.0 because enabled
--
host.ioBroker | 2023-02-20 14:35:58.486 | error | instance system.adapter.zigbee2mqtt.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.ioBroker | 2023-02-20 14:35:58.486 | error | Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
host.ioBroker | 2023-02-20 14:35:58.486 | error | Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:1015:30)
host.ioBroker | 2023-02-20 14:35:58.486 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/aedes/aedes.js:11:16)
host.ioBroker | 2023-02-20 14:35:58.486 | error | Caught by controller[0]: at require (internal/modules/cjs/helpers.js:74:18)
host.ioBroker | 2023-02-20 14:35:58.486 | error | Caught by controller[0]: at Module.require (internal/modules/cjs/loader.js:903:19)
host.ioBroker | 2023-02-20 14:35:58.485 | error | Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:724:14)
host.ioBroker | 2023-02-20 14:35:58.485 | error | Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:879:32)
host.ioBroker | 2023-02-20 14:35:58.485 | error | Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
host.ioBroker | 2023-02-20 14:35:58.485 | error | Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:979:27)
host.ioBroker | 2023-02-20 14:35:58.485 | error | Caught by controller[0]: at wrapSafe (internal/modules/cjs/loader.js:931:16)
host.ioBroker | 2023-02-20 14:35:58.485 | error | Caught by controller[0]: SyntaxError: Unexpected token '.'
host.ioBroker | 2023-02-20 14:35:58.484 | error | Caught by controller[0]: ^
host.ioBroker | 2023-02-20 14:35:58.484 | error | Caught by controller[0]: } else if (storedSub?.qos > 0) {
host.ioBroker | 2023-02-20 14:35:58.484 | error | Caught by controller[0]: /opt/iobroker/node_modules/aedes-persistence/persistence.js:113

**Comment by the-duke** [comment]
Hat sich erledigt nach einem update auf nodejs version 16 mit der aedes-persistence klar kommt
