### ISSUE TITLE
No connection to Z2M instance after update to 2.13.6 with JS-Controller 4.0.19

### ISSUE THREAD

**Issue by nukleuz80** [arteck/ioBroker.zigbee2mqtt#335]
### What happened?

After Updating the adapter to Version 2.13.6 i got the errors in logs:

After the update i created the auth_token with my custom passphrase WITHOUT special characters like: _thatsmycustomtoken_

The Z2M-WebUI asked for the token after Z2M restart - after copy & paste it still works. So the config in Z2M is surely correct.

In the adapter settings i do the same but it´s not running.

BUT without auth_token it is also not running.

### What did you expect to happen?

A successfully connection to Z2M instance.

### Adapter version

2.13.6

### Adapter Config Log

```
host.phoscon
2024-04-19 16:17:27.145	info	Restart adapter system.adapter.zigbee2mqtt.0 because enabled

host.phoscon
2024-04-19 16:17:27.145	error	instance system.adapter.zigbee2mqtt.0 terminated with code 1 (JS_CONTROLLER_STOPPED)

host.phoscon
2024-04-19 16:17:27.145	error	Caught by controller[0]: Node.js v18.20.2

host.phoscon
2024-04-19 16:17:27.144	error	Caught by controller[0]: }

host.phoscon
2024-04-19 16:17:27.144	error	Caught by controller[0]: code: 'ERR_INVALID_ARG_VALUE'

host.phoscon
2024-04-19 16:17:27.144	error	Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.zigbee2mqtt/node_modules/@iobroker/adapter-core/build/cjs/controllerTools.js:34:22) {

host.phoscon
2024-04-19 16:17:27.144	error	Caught by controller[0]: at require (node:internal/modules/helpers:177:18)

host.phoscon
2024-04-19 16:17:27.144	error	Caught by controller[0]: at Module.require (node:internal/modules/cjs/loader:1231:19)

host.phoscon
2024-04-19 16:17:27.144	error	Caught by controller[0]: at Module._load (node:internal/modules/cjs/loader:1019:12)

host.phoscon
2024-04-19 16:17:27.144	error	Caught by controller[0]: at Module.load (node:internal/modules/cjs/loader:1203:32)

host.phoscon
2024-04-19 16:17:27.144	error	Caught by controller[0]: at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)

host.phoscon
2024-04-19 16:17:27.143	error	Caught by controller[0]: at Module._compile (node:internal/modules/cjs/loader:1364:14)

host.phoscon
2024-04-19 16:17:27.143	error	Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.zigbee2mqtt/node_modules/@iobroker/adapter-core/build/cjs/helpers.js:36:53)

host.phoscon
2024-04-19 16:17:27.143	error	Caught by controller[0]: at createRequire (node:internal/modules/cjs/loader:1501:13)

host.phoscon
2024-04-19 16:17:27.143	error	Caught by controller[0]: at new NodeError (node:internal/errors:405:5)

host.phoscon
2024-04-19 16:17:27.143	error	Caught by controller[0]: TypeError [ERR_INVALID_ARG_VALUE]: The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received 'file:// /opt/iobroker/node_modules/iobroker.zigbee2mqtt/node_modules/@iobroker/adapter-core/build/cjs/helpers.js'

host.phoscon
2024-04-19 16:17:27.143	error	Caught by controller[0]: ^
host.phoscon
2024-04-19 16:17:27.142	error	Caught by controller[0]: throw new ERR_INVALID_ARG_VALUE('filename', filename,

host.phoscon
2024-04-19 16:17:27.142	error	Caught by controller[0]: node:internal/modules/cjs/loader:1501

host.phoscon
2024-04-19 16:17:26.566	info	instance system.adapter.zigbee2mqtt.0 started with pid 20151

host.phoscon
2024-04-19 16:16:56.342	info	Restart adapter system.adapter.zigbee2mqtt.0 because enabled
```

**Comment by arteck** [comment]
install again plz

**Comment by nukleuz80** [comment]
No success with install again... Could the controller be the problem?

**Comment by nukleuz80** [comment]
I updated the js controller to 5.0.19 and deleted the adapter. After new Installation the error comes up again … 

Could you please check it out or give me a hint how to fix it? Thanks

**Comment by nukleuz80** [comment]
This was the solution:

https://forum.iobroker.net/topic/74237/l%C3%B6sung-f%C3%BCr-fehler-typeerror-err_invalid_arg_value

Thanks
