### ISSUE TITLE
Adapter is looping into crash

### ISSUE THREAD

**Issue by tarikweiss** [arteck/ioBroker.zigbee2mqtt#411]
### What happened?

The adapter is looping into a crash due to issues for writing states.

### What did you expect to happen?

The adapter does not crash

### How to reproduce it (minimal and precise)

I cannot tell what leads to this issue.

### Adapter version

2.13.11

### Adapter Config Log

zigbee2mqtt.0
2024-12-02 07:43:08.818	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

zigbee2mqtt.0
2024-12-02 07:43:08.818	error	unhandled promise rejection: Cannot set properties of undefined (setting 'occupied_heating_setpoint')

zigbee2mqtt.0
2024-12-02 07:43:08.818	error	TypeError: Cannot set properties of undefined (setting 'occupied_heating_setpoint') at DeviceController.createOrUpdateDevices (/opt/iobroker/node_modules/iobroker.zigbee2mqtt/lib/deviceController.js:316:69) at runNextTicks (node:internal/process/task_queues:60:5) at process.processImmediate (node:internal/timers:454:9) at async Zigbee2mqtt.messageParse (/opt/iobroker/node_modules/iobroker.zigbee2mqtt/main.js:205:17)

zigbee2mqtt.0
2024-12-02 07:43:08.819	error	Cannot set properties of undefined (setting 'occupied_heating_setpoint')

**Comment by arteck** [comment]
check new version
